### ISSUE TITLE
Rustfmt

### ISSUE THREAD

**Issue by killercup** [killercup/assert_cli#48]
Rustfmt the whole codebase and add a CI step to check the formatting.

@epage linked to [this config](https://github.com/cobalt-org/cobalt.rs/blob/41a71ac6296f129e6251753b3933ca9a2795345e/.travis.yml#L29), but I'm more inclined to do it like we do our clippy build, and use rustfmt-nightly just [like diesel](https://github.com/diesel-rs/diesel/blob/c6788f17965563194688e569dfb0131c5a50504b/.travis.yml#L53-L60).

**Comment by epage** [comment]
Yeah, old rustfmt was to avoid another nightly dependency.

Note that the diesel logic will probably run into problems with travis caches when they upgrade rustfmt.  The old version will still exist, so nothing will necessitate an upgrade.  Combinging it with my logic would help because it checks if rustfmt is installed and is the expected version.  If this fails, it force installs.

**Comment by killercup** [comment]
Tbh I'd just `cargo +nightly-2017-10-09 install rustfmt-nightly --vers "0.2.8"` and be done with it. IIRC, we don't cache these things anyway.

**Comment by epage** [comment]
Fixed by #49
