### ISSUE TITLE
Output satisfies predicate?

### ISSUE THREAD

**Issue by dsprenkels** [killercup/assert_cli#55]
Thanks for this awesome library!

I would like to check if the command's output is from a specific format. I am specifically dealing with formats like this:

```
0156dc3c96b0939fa...
02fab783bdfc017dd...
```

with the first byte being a counted integer, and the rest random. So I would like to check if the binary lengths are correct and if the first byte is `01, 02, ...`.

Is it possible to pass a function to a `OutputAssertionBuilder` method which allows me to check by predicate?

If not, I would like to propose one (`OutputAssertionBuilder::satisfy`), which you can call with a function which checks if the string satisfies a given predicate.

Example type signature:

```
fn satisfies<F>(pred: F) -> Assert
    where F : FnOnce(&str) -> bool
```

**Comment by epage** [comment]
Currently, we only support exact matches and substring matches.

The idea is welcome.  In #20, we talk about regex matches and `fn` matches. For an `fn`, we either need to `Box` it or have a state-less pointer.

Your suggestion for the name is `satisfies`.  In the API, this would look like
```rust
fn all_lowercase(output: &str) -> bool {
   ...
}

...
    .stdout().satisfies(all_lowercase)
    .unwrap();
```

I don't (yet?) have much in the way of opinions on the name.  Is there any kind of precedence that we should be consistent with?

**Comment by killercup** [comment]
The std lib has an abstraction like that. I think it was Pattern, in str or
something like that.


Ed Page <notifications@github.com> schrieb am Mo. 16. Okt. 2017 um 20:05:

**Comment by dsprenkels** [comment]
[Could it be something like this?](https://github.com/killercup/assert_cli/compare/master...dsprenkels:predicates?expand=1)

It changes the code style, but I think that the `OutputAssertion` would become a bit more flexible. There is however the issue of error reporting, which gets a little harder. For the error building, I was thinking about taking an extra field in the `OutputAssertion` struct containing an error builder. Another option could be for `pred` to return a `Result` and putting the error building in the `assert.rs` code.

Or ditch this plan altogether, cause closures are not very pleasant to work with. :wink:

**Comment by epage** [comment]
A lot of the value is the rich error reporting, we need to be sure to preserve that.

While this might not need Debug/Clone, I still hesitate when not supporting such basic traits.

Until someone has a use case for it, we could avoid unifying the code branches and have a stateless function pointer rather than a stateful one in a `Box`.

**Comment by dsprenkels** [comment]
I restored the error reporting and restored the Debug/Clone trait implementations. Currently I use a `Rc` for the `Clone` functionality, which looks a bit ugly but is not really a problem (?).

I also implemented the functions that I mentioned before. Shall I open a PR?

(Compare changes: https://github.com/killercup/assert_cli/compare/master...dsprenkels:predicates?expand=1)

**Comment by epage** [comment]
Huh, somehow lost my post

> I don't really understand what you mean by your last statement, do you mean using &'a Fn everywhere, instead of a boxed type?

I was thinking of a [function pointer rather than a function trait](https://doc.rust-lang.org/book/second-edition/ch19-05-advanced-functions-and-closures.html) unless there is a use case where we need the trait instead.

> Shall I open a pull request?

Yes please, it'll provide a better forum for talking about the code.

Also, maybe I'm just being crotchety but I'm somewhat preferring the enum approach rather than unifying everything behind a boxed Fn trait.  Thoughts?

**Comment by epage** [comment]
FYI #74 will cause a lot of merge conflicts.  I went ahead and reworked your ideas in a branch of #74 but haven't pushed it yet until #74 is in.

**Comment by epage** [comment]
btw my current thought on what this API could look like
- `satisfies(Fn(String) -> bool, message: String)`
  - `message` is there since we can't gleam anything from the `Fn`
- `satisfies_ok(Fn(String) -> Result<(), Box<Error>>)`
  - `Box<Error>` so that the caller can provide a completely custom error message to explain why their assertion failed.
