### ISSUE TITLE
Fuzzy matching

### ISSUE THREAD

**Issue by Lindenk** [killercup/assert_cli#8]
There should be a way to check output in a more flexible manner, such as by using a regex, or an array of possible values.

A couple possible implementations off the top of my head could be:

``` rust
/// Match against any in a vec
assert_cli!("shuf", &["-i", "1-2", "-n", "1"] => Success, &["1", "2"]);
```

``` rust
/// Match with regex
assert_cli!("shuf", &["-i", "1-99", "-n", "1"] => Success, r"[0-9]+");
```

**Comment by killercup** [comment]
I agree, this is a feature that would come in really handy. Like I mention
in the other issue, I'd like to have it behind a cargo feature though (to
not force the regex dependency on everyone).

I'm not sure how you'd differentiate between normal and fuzzy matching.
Prefixing a string literal with an `r` means it should be treated as a raw
literal (no escape sequences), so I don't think we can use that. Maybe use
`~>` instead of `=>`?
Linden Krouse <notifications@github.com> schrieb am So. 10. Juli 2016 um
17:23:

**Comment by Lindenk** [comment]
Of course.

I agree that prefixing it with `r` is not a great idea, I just wanted to make the issue so it wasn't forgotten. `~>` sounds like a good idea, although it might be a little difficult to pick out since it isn't part of the output-to-match argument, but I like the flavor of it. Prefixing with `regex` might be too verbose, what about prefixing the output string with `~`?

```
/// Match with regex
assert_cli!("shuf", &["-i", "1-99", "-n", "1"] => Success, ~"[0-9]+");
```
